extMimeTypes = dict()
  
extMimeTypes["html"] = "text/html"
extMimeTypes["htm"] = "text/html"
extMimeTypes["png"] = "image/png"
extMimeTypes["tiff"] = "image/tiff"
extMimeTypes["tif"] = "image/tiff"
extMimeTypes["jpeg"] = "image/jpeg"
extMimeTypes["jpg"] = "image/jpeg"
extMimeTypes["gif"] = "image/gif"
extMimeTypes["svg"] = "image/svg+xml"
extMimeTypes["txt"] = "text/plain"
extMimeTypes["xml"] = "text/xml"
extMimeTypes["epub"] = "application/epub+zip"
extMimeTypes["pdf"] = "application/pdf"
extMimeTypes["ogg"] = "audio/ogg"
extMimeTypes["ogv"] = "video/ogg"
extMimeTypes["js"] = "application/javascript"
extMimeTypes["json"] = "application/json"
extMimeTypes["css"] = "text/css"
extMimeTypes["otf"] = "application/vnd.ms-opentype"
extMimeTypes["eot"] = "application/vnd.ms-fontobject"
extMimeTypes["ttf"] = "application/font-ttf"
extMimeTypes["woff"] = "application/font-woff"
extMimeTypes["woff2"] = "application/font-woff2"
extMimeTypes["vtt"] = "text/vtt"
extMimeTypes["webm"] = "video/webm"
extMimeTypes["mp4"] = "video/mp4"
extMimeTypes["doc"] = "application/msword"
extMimeTypes["docx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
extMimeTypes["ppt"] = "application/vnd.ms-powerpoint"
extMimeTypes["odt"] = "application/vnd.oasis.opendocument.text"
extMimeTypes["odp"] = "application/vnd.oasis.opendocument.text"
extMimeTypes["zip"] = "application/zip"
extMimeTypes["wasm"] = "application/wasm"


def get_mime_from_extension(ext):
    return extMimeTypes.get(ext.lower(), '')